### ISSUE TITLE
DDG gives me 403 periodically.

### ISSUE THREAD

**Issue by pcarinhas** [deedy5/duckduckgo_search#100]
I can only do a few queries until I get a 403 on my dev box. Is there anything I should do I avoid that?
If I wait for a period it again allows me to continue.

Using their 403 link, it works in the browser so maybe they don't want non-browser access.
For example:

This failed: 

> ```ddgs news -k "ukraine war"  -m 11```

But this worked: 

> https://duckduckgo.com/news.js?l=wt-wt&o=json&noamp=1&q=ukraine%20war&vqd=4-332504019714920169446792928607979845974&p=-1&df=&s=0

**Comment by deedy5** [comment]
```Is there anything I should do I avoid that?```
Use a proxy or call the function less often

**Comment by pcarinhas** [comment]
Can I extract the vqi from the response and use that in subsequent calls? That seems to work with curl.
