### ISSUE TITLE
ImportError: cannot import name 'DDGS' from 'duckduckgo_search'

### ISSUE THREAD

**Issue by wilmerhenao** [deedy5/duckduckgo_search#102]
When I try 

`from duckduckgo_search import DDGS`

I'm on version 3.8.3 and my python is 3.11.2

**Comment by deedy5** [comment]
If you do not want to create and use a virtual environment, just install the package this way:
```python
python -m pip install -U duckduckgo_search --break-system-packages
```
You can check if a package is installed in the terminal with the command:
```python
ddgs version
```
