### ISSUE TITLE
TypeError: request() got an unexpected keyword argument 'follow_redirects'

### ISSUE THREAD

**Issue by h9052300** [deedy5/duckduckgo_search#112]
**Describe the bug**
TypeError: request() got an unexpected keyword argument 'follow_redirects'

**Debug log**
TypeError: request() got an unexpected keyword argument 'follow_redirects'

**Specify this information**
 - OS: Win 11 
 - environment python 3.9
 - duckduckgo_search version 3.8.5

**Comment by deedy5** [comment]
show the code where you got this error

**Comment by h9052300** [comment]
from duckduckgo_search import DDGS

with DDGS() as ddgs:
    for r in ddgs.text('live free or die', region='wt-wt', safesearch='off', timelimit='y'):
        print(r)

**Comment by deedy5** [comment]
I can't reproduce the problem.
Try reinstalling the package.
```python3
pip install -I -U duckduckgo_search
```

**Comment by IGamesI** [comment]
I also get the same error using the sample provides in the text() section of the main documentation.
Code:
```
from duckduckgo_search import DDGS

with DDGS(timeout=20) as ddgs:
    for r in ddgs.text("something you need"):
        print(r)
```

Output:
`TypeError: Client.request() got an unexpected keyword argument 'follow_redirects'`

I can confirm that the package is installed and imported.

**Comment by deedy5** [comment]
Thanks for participating.
Please show me the result of this code.

```python3
import logging
from duckduckgo_search import DDGS

logging.basicConfig(level=logging.INFO)

with DDGS(timeout=20) as ddgs:
    for r in ddgs.text("aaa"):
        print(r)
```
