### ISSUE TITLE
AssertionError: error in getting vqd Issue

### ISSUE THREAD

**Issue by twinstarhub** [deedy5/duckduckgo_search#113]
**Describe the bug**
AssertionError: error in getting vqd
when i run the query "site:linkedin.com Anna Storåkers" to search profile in python.
the error is occurring. Only on the code. in the browser the query is working well.

**Debug log**
Add `logging.basicConfig(level=logging.DEBUG)` to the beginning of your script and attach log to the issue.

**Screenshots**
![image](https://github.com/deedy5/duckduckgo_search/assets/108885340/3af1a73d-f05c-4b54-b14c-0a953c7efffe)

**Specify this information**
 - OS windows
 - environment : python3.10.6
 - duckduckgo_search version latest version few days ago updated

**Comment by twinstarhub** [comment]
![image](https://github.com/deedy5/duckduckgo_search/assets/108885340/6f2073c9-748a-4048-9458-a668906380ab)

**Comment by deedy5** [comment]
try using a proxy server

**Comment by twinstarhub** [comment]
residential proxy i used
but one more thing, the result is really limited here

**Comment by twinstarhub** [comment]
30~50 result per one query

**Comment by deedy5** [comment]
That's the way it should be. 
Now the text search on duckduckgo.com gives a maximum of about 50 results, although it used to be about 200.

**Comment by twinstarhub** [comment]
Thank you for your support. How can i increase the result count? do you know about another search engine? I need more, and more results. Actually i am gonna use google search engine. but the google custom search is high price and we can't use that for industry.
So i am looking for search engine that is programmable and having more results

**Comment by deedy5** [comment]
Just send several different queries, but phrase them differently (synonym words or other phrases, but with the same meaning). And then aggregate all the results.

**Comment by twinstarhub** [comment]
but there are performance problems, i am gonna make some search engine depend on the duckduckgo search engine. but if i increase them, and apply proxy, in this case it might slow down. could you kindly share your contact info. I am really interested in your library. and checked the github repo code carefully.

**Comment by twinstarhub** [comment]
i have really urgent project. i used your library and i need your help. 
gmail or telegram or linkedin?

**Comment by twinstarhub** [comment]
which communication app is available for you?

**Comment by deedy5** [comment]
I've sent you an e-mail

**Comment by twinstarhub** [comment]
i just invited you on google chat
