### ISSUE TITLE
Get French result...

### ISSUE THREAD

**Issue by Bigdimuss** [deedy5/duckduckgo_search#124]
Hello, 
Thx for your great job !
how can i get french result ? i see in "https://links.duckduckgo.com/d.js" a 'ct' params with "FR" value, but when i request the result was in english, I don't know why... 

can you help me ? 

thx.

**Comment by deedy5** [comment]
Hi.
It definitely works with backend="html":
https://ddgs.deedy5.repl.co/text?q=paris&region=fr-fr&backend=html
Look at the source code.

**Comment by Bigdimuss** [comment]
Its work too with : bing_market='fr_FR'

**Comment by deedy5** [comment]
Thanks for the tip, fixed in version v3.9.3
