### ISSUE TITLE
Using Tor browser causes redirects and then fails

### ISSUE THREAD

**Issue by roeehub** [deedy5/duckduckgo_search#131]
**Describe the bug**
I started to get too frequent 202's on my searches so I decided to try proxies (I think my IP is marked/limited...)
For some reason, if we look at theses two snippets (examples like in the docs):

(1) With the tor browser proxy
with DDGS(proxies="socks5://localhost:9150", timeout=20) as ddgs:
    for r in ddgs.text("halloween site:www.nyt.com", max_results=50):
        print(r)

(2) Without the tor browser proxy:
with DDGS(timeout=20) as ddgs:
    for r in ddgs.text("halloween site:www.nyt.com", max_results=50):
        print(r)

(2) worked great in the past but now barely works (so I'm trying the proxy approach)
(1) gives me the output below

**Debug log**
INFO:httpx:HTTP Request: POST https://duckduckgo.com "HTTP/2 200 OK"
INFO:httpx:HTTP Request: GET https://links.duckduckgo.com/d.js?q=halloween%20site%3Awww.nyt.com&kl=wt-wt&l=wt-wt&bing_market=wt-WT&s=0&df=y&vqd=4-10289302446110504522790222982708518478&o=json&sp=0&ex=-1 "HTTP/2 301 Moved Permanently"
INFO:httpx:HTTP Request: GET https://links.duckduckgo.com/506-01.js?q=halloween%20site%3Awww.nyt.com "HTTP/2 200 OK"
WARNING:duckduckgo_search.duckduckgo_search:_get_url() https://links.duckduckgo.com/d.js HTTPError 
INFO:httpx:HTTP Request: GET https://links.duckduckgo.com/d.js?q=halloween%20site%3Awww.nyt.com&kl=wt-wt&l=wt-wt&bing_market=wt-WT&s=0&df=y&vqd=4-10289302446110504522790222982708518478&o=json&sp=0&ex=-1 "HTTP/2 301 Moved Permanently"
INFO:httpx:HTTP Request: GET https://links.duckduckgo.com/506-01.js?q=halloween%20site%3Awww.nyt.com "HTTP/2 200 OK"
WARNING:duckduckgo_search.duckduckgo_search:_get_url() https://links.duckduckgo.com/d.js HTTPError 
INFO:httpx:HTTP Request: GET https://links.duckduckgo.com/d.js?q=halloween%20site%3Awww.nyt.com&kl=wt-wt&l=wt-wt&bing_market=wt-WT&s=0&df=y&vqd=4-10289302446110504522790222982708518478&o=json&sp=0&ex=-1 "HTTP/2 301 Moved Permanently"
INFO:httpx:HTTP Request: GET https://links.duckduckgo.com/506-01.js?q=halloween%20site%3Awww.nyt.com "HTTP/2 200 OK"
WARNING:duckduckgo_search.duckduckgo_search:_get_url() https://links.duckduckgo.com/d.js HTTPError 

...

And then throws HTTPError.

**Specify this information**
 - OS: MacOS Ventura 13.4, M2
 - duckduckgo_search version: duckduckgo-search==3.9.3

I do have a feeling that I'm missing something and would appreciate any help :)

**Comment by CyberTimon** [comment]
I have exactly the same issue since yesterday. Hope this get's fixed soon.

**Comment by deedy5** [comment]
Hi. Try upgrading to 3.9.5, it should work.

**Comment by CyberTimon** [comment]
Thank you - after upgrading it works again. I think we can close this issue.

**Comment by roeehub** [comment]
Thank you!
Sadly I still seem to get an error after a 302:
INFO:httpx:HTTP Request: POST https://duckduckgo.com "HTTP/2 302 Found"
INFO:httpx:HTTP Request: GET https://duckduckgo.com/static/duckduckgo/418.html?bno=d044&is_tor=1&is_ar=0&is_netp=0 "HTTP/2 200 OK"
Traceback (most recent call last):
...
AssertionError: error in getting vqd

**Comment by roeehub** [comment]
Thank you!
Sadly I still seem to get an error after a 302:
INFO:httpx:HTTP Request: POST https://duckduckgo.com "HTTP/2 302 Found"
INFO:httpx:HTTP Request: GET https://duckduckgo.com/static/duckduckgo/418.html?bno=d044&is_tor=1&is_ar=0&is_netp=0 "HTTP/2 200 OK"
Traceback (most recent call last):
...
AssertionError: error in getting vqd
