### ISSUE TITLE
Image search doesn't work

### ISSUE THREAD

**Issue by jakelazylion** [deedy5/duckduckgo_search#136]
Image search keeps failing with following error message:

_get_url() https://duckduckgo.com/i.js HTTPStatusError Client error '403 Forbidden' for url 'https://duckduckgo.com/i.js?l=wt-wt&o=json&q=Spigen%20iphone%2015%20case&vqd=4-299838449604213088837360599828098249376&f=%2C%2C%2C%2C%2C&p=1'

**Comment by jakelazylion** [comment]
Adding `"Accept-Encoding": "gzip, deflate, br",` under headers seems fixing the problem

**Comment by deedy5** [comment]
fixed in v3.9.8

**Comment by kraslav4ik** [comment]
Hi! Still facing this issue (even after update to 3.9.8)

**Comment by tbonus** [comment]
issue still persists with v3.9.9

**Comment by kBashar** [comment]
Getting the same error in v3.9.8
