### ISSUE TITLE
Problem with advertisements in search results

### ISSUE THREAD

**Issue by lw4z** [deedy5/duckduckgo_search#139]
**Describe the bug**
In all searches, an advertisement link is appearing initially in the results. I noticed this outcome only in the latest version 3.9.8.

code:

```
from duckduckgo_search import DDGS
from itertools import islice

web_results = []

with DDGS(timeout=10) as ddgs:
    result_web_search = ddgs.text(
        keywords='dog',
        region='br-pt',
        safesearch='off',
        timelimit='',
        backend='html',
    )
    
    for r in islice(result_web_search, 3):
        web_results.append(r)
list({i['href']: i for i in web_results}.values())
```

**Screenshots**
![image](https://github.com/deedy5/duckduckgo_search/assets/7463411/2fa6e016-d3cc-4cc9-9e4f-336b538a65b7)

![image](https://github.com/deedy5/duckduckgo_search/assets/7463411/8df234cb-9ead-4ceb-88bd-d886f5f4c11d)

**Specify this information**
 - Manjaro Linux 
 - Python 3.11.5
 - duckduckgo_search version: 3.9.8

**Comment by deedy5** [comment]
Thanks for the research.
Fixed in v3.9.9
