### ISSUE TITLE
Issue since 3.9.10

### ISSUE THREAD

**Issue by zimpstar** [deedy5/duckduckgo_search#150]
Hi there,

First of all. Awesome package. Love it.

Howver, ever since the 3.9.10 & 3.9.11 updates, I'm getting this error:

Search Term #1 : what is seo
Error occurred while searching for 'what is seo': _get_url() https://duckduckgo.com
URL 1: None
Search Term #2 : what is cro
Error occurred while searching for 'what is cro': _get_url() https://duckduckgo.com
URL 2: None
Generic URLs: None

It would seem like it's just not grabbing any urls at all from the results anymore. I've spent about 8 hours trying to fix this now and was hoping to find some help here, hope that is OK :)

**This is the part of the code I'm using:**

```
def scraper(main_keyword, secondary_keyword_1, secondary_keyword_2, title):
    search_term = secondary_keyword_1
    print(f"Search Term #1 : {search_term}")
    
    wikipedia_url = None

    try:
        with DDGS() as ddgs:
            wikipedia_results = [r for r in ddgs.text(search_term, max_results=1)]
            if wikipedia_results:
                wikipedia_url = wikipedia_results[0]['href']
    except Exception as e:
        print(f"Error occurred while searching for '{search_term}': {e}")

    print(f"URL 1: {wikipedia_url}")

    time.sleep(5)

    secondary_search_term = secondary_keyword_2
    print(f"Search Term #2 : {secondary_search_term}")
    generic_url = None

    try:
        with DDGS() as ddgs:
            generic_results = [r for r in ddgs.text(secondary_search_term, max_results=1)]
            if generic_results:
                generic_url = generic_results[0]['href']
    except Exception as e:
        print(f"Error occurred while searching for '{secondary_search_term}': {e}")

    print(f"URL 2: {generic_url}")
    print(f"Generic URLs: {generic_url}")
```
    
    
**Please excuse the horrendous use of variable names, I'm new to this!**

**Comment by zimpstar** [comment]
Sorry for the spam but after trying again for quite some time I also get rate limited .. I havent sent any requests in 48 hours +

**Comment by deedy5** [comment]
update to v3.9.11

**Comment by zimpstar** [comment]
Sorry if I was unclear, this is indeed v3.9.11

**Comment by deedy5** [comment]
All tests passed successfully. 
Try to reinstall package `pip install -I duckduckgo_search`.
Try to use proxy.

**Comment by kostum123** [comment]
This error continues. When I run the same code on Google Colab, Google Colab’s server IP is not blocked, but when I run it on my home computer, my home IP is not allowed. I really can’t understand this logic. Moreover, even though no request has been made from my home IP, it immediately gives an error message. I guess with the recent changes, you have started to block residential IPs as well. I hope this is a mistake because it’s very absurd to block residential users’ IPs while not blocking datacenter IPs.

**Comment by deedy5** [comment]
The site blocks requests with tls-fingerprint. 
I had to switch from httpx to curl-cffi. 
Now everything works as it should, hopefully for a long time.

**Comment by ShubhamNandalwar8** [comment]
> The site blocks requests with tls-fingerprint. I had to switch from httpx to curl-cffi. Now everything works as it should, hopefully for a long time.

can you please tell me how did you do that?

**Comment by deedy5** [comment]
I don't understand the point of the question.

**Comment by ShubhamNandalwar8** [comment]
can you provide the code  to switch from httpx to curl-cffi.

> I don't understand the point of the question.

**Comment by deedy5** [comment]
Check it out here: https://github.com/yifeikong/curl_cffi
