### ISSUE TITLE
ImportError: cannot import name 'DDGS' from partially initialized module 'duckduckgo_search'

### ISSUE THREAD

**Issue by worm128** [deedy5/duckduckgo_search#162]
我已经安装了pip install -U duckduckgo_search
并且ddgs version显示版本4.1.0
搜索ddgs text -k "china is a global threat" -p socks5://localhost:10806也有结果
当时python导入DDGS包时候报错【ImportError: cannot import name 'DDGS' from partially initialized module 'duckduckgo_search'】
<img width="1104" alt="微信图片_20231221163638" src="https://github.com/deedy5/duckduckgo_search/assets/29749635/99c33992-62ce-4d5c-97b8-209f322921eb">

**Comment by deedy5** [comment]
Rename your script. 
You are importing duckduckgo_search into duckduckgo_search.py
