### ISSUE TITLE
DDGS Map Search

### ISSUE THREAD

**Issue by madhatter349** [deedy5/duckduckgo_search#187]
`from duckduckgo_search import DDGS

with DDGS() as ddgs:
    for r in ddgs.maps("coffee shops", postalcode="10001", max_results=10):
        print(r)`

When trying to search this for example I get no results, the only map search that seems to work is if you use "place".

Thanks

**Comment by deedy5** [comment]
1) fixed in v4.4.3, update `pip install -U duckduckgo_search`
2) zip-codes may be the same in different countries - [10001](https://nominatim.openstreetmap.org/ui/search.html?postalcode=10001), so with `postalcode` also use at least `country` parameter

**Comment by madhatter349** [comment]
@deedy5 thank you so much, that fixed it!

It may be a quirk on the other end, but when searching DDG manually I can find two specific locations tied to a zip code, but when pulling via code, it only finds one of them. I believe that when I searched multiple surrounding zip codes and aggregated the data, both finally popped up... Thought was quite interesting.
