### ISSUE TITLE
Can this work with Python 3.12? 

### ISSUE THREAD

**Issue by hgoona** [deedy5/duckduckgo_search#188]
Can DDGS work with Python 3.12? I noted it says >=3.8 ?

I'm using this package, via a LangChain "Tool" library which is built on top of this library, and I'm seeing `curl_cffi` errors in my vscode terminal. 

I'm trying to find out what is causing this error:
```Task was destroyed but it is pending!
task: <Task cancelling name='Task-98' coro=<AsyncCurl._force_timeout() running at C:\Users\ ... \Lib\site-packages\curl_cffi\aio.py:168> wait_for=<Future cancelled>>```

**Comment by deedy5** [comment]
It's a bug in curl-cffi.
Fixed in https://github.com/yifeikong/curl_cffi/pull/245
Wait for a new version of curl-cffi
