### ISSUE TITLE
What is the exact rate limit of DDG?

### ISSUE THREAD

**Issue by heesuju** [deedy5/duckduckgo_search#198]
Hello, 

I'm using duckduckgo_search version 5.1.0.
In my code, I'm using "AsyncDDGS.text(keyword)" in a for loop.
I'm iterating through the loop with an interval of 10 seconds using "await asyncio.sleep(10)".

However, after 5-6 search requests, I'm getting a rate limit error.
Any subsequent requests trigger a rate limit error as well for about 10-15 minutes.
Until now I thought that the rate limit was 1-2 request per 10 seconds, but this doesn't seem to be the case.

Is there a total amount of requests that I'm allowed to send?
Any help would be appreciated. 
Thank you in advance.

**Comment by deedy5** [comment]
Hi, show me the code.

**Comment by phamxtien** [comment]
After upgrade to 5.1.0 it returns error

_aget_url() https://duckduckgo.com RequestsError: Impersonating BrowserType.chrome120 is not supported

**Comment by deedy5** [comment]
@phamxtien 
Some kind of problem with `curl-cffi`. 
Try to reinstall duckduckgo_search:
`pip install -I duckduckgo_search`

**Comment by phamxtien** [comment]
> @phamxtien Some kind of problem with `curl-cffi`. Try to reinstall duckduckgo_search: `pip install -I duckduckgo_search`

I follow your guide but still get errror

**Comment by deedy5** [comment]
are you importing `requests`?

**Comment by phamxtien** [comment]
> are you importing `requests`?

Yes, i import requests already
I miss it when create above comment

**Comment by deedy5** [comment]
I don't see the above error when I run your code.
Reinstall duckduckgo_search in the virtual environment from which you are running the code.

**Comment by phamxtien** [comment]
I think this make it error
![image](https://github.com/deedy5/duckduckgo_search/assets/33739597/70836baf-7682-475b-8d01-e97e42f999bf)
and I'm still stuck :(

**Comment by heesuju** [comment]
> Hi, show me the code.

DUCKDUCKGO_MAX_ATTEMPTS = 3

async def web_search(query: str, num_results: int = 8) -> list[dict]:
    search_results = []
    attempts = 0

    while attempts < DUCKDUCKGO_MAX_ATTEMPTS:
        if not query:
            return json.dumps(search_results)

        async with AsyncDDGS() as ddgs:
            results = await ddgs.text(query, safesearch='on', max_results=num_results, backend="html")
            search_results = list(islice(results, num_results))

        if search_results:
            break

        await asyncio.sleep(1)
        attempts += 1

    return search_results

async def main(url:str):
	
	keywords = ["keyword1", "keyword2", "keyword3", "keyword4", "keyword5"]
    for i in range(len(keywords)):
        results = await search_keyword(keywords[i], 10)
        await asyncio.sleep(10)

**Comment by deedy5** [comment]
Try to use `backend='api'`, it's less likely to block.

**Comment by heesuju** [comment]
Completely forgot to mention that I switched over to 'html' from 'api' after my ip started getting blocked.
I guess my only option is using proxies. 
Thank you for the help!

**Comment by iwo9** [comment]
Hi - did using proxies resolve the issue? I'm having the same problem - used to work fine, now I keep getting the rate limit exception after 5-6 search runs. Have to wait a while before it can run properly again. Was trying to see if there's a way to actually pay for duckduckgo-search so that I can guarantee it'll work for what I need, but can't find that either.

**Comment by deedy5** [comment]
@iwo9 
Just use a rotating proxy 
https://github.com/deedy5/duckduckgo_search?tab=readme-ov-file#proxy
