### ISSUE TITLE
getting ratelimit exception on all existing code.

### ISSUE THREAD

**Issue by steelliberty** [deedy5/duckduckgo_search#204]
Hi -- 

I am getting this exception : duckduckgo_search.exceptions.DuckDuckGoSearchException: _aget_url() https://links.duckduckgo.com/d.js DuckDuckGoSearchException: Ratelimit

I have existing code that worked for 6 weeks and stopped today-- it is was in this form :  (query was given)
        with DDGS() as ddgs:
            search_results_list = [r for r in ddgs.text(f"{query}", max_results=num_results,region="us-en",
            safesearch="off",
            timelimit="m",)]

Then I tried an example from the site:
results = DDGS().text('live free or die', region='wt-wt', safesearch='off', timelimit='y', max_results=10)

and this 
results = DDGS().text("python programming", max_results=5)
print(results)

I was running 4.3
Now I am running 5.1 (unable to get 5.2 to build wheel) 
Same results

thank you --

**Comment by deedy5** [comment]
Hi.
There were some changes in the api today, so the package stopped working.
Fixed in version v5.2.1

**Comment by jasonoh1998** [comment]
`pip install --upgrade duckduckgo-search`
`Successfully installed duckduckgo-search-5.2.1 orjson-3.10.0`

works great now thanks :)
