### ISSUE TITLE
cli: ddgs searches (news, text) hang after returning 1 result

### ISSUE THREAD

**Issue by jonny7737** [deedy5/duckduckgo_search#214]
**Before you open an issue:**
- [Y ] I have the latest version. (Check: `ddgs version`. Update: `pip install -U duckduckgo_search`)</br>
- [ Y] I tried reinstalling the library. (`pip install -I duckduckgo_search`)
- [ Y] https://duckduckgo.com is accessible in my browser
- [ N] I tried using a proxy (the site may block ip for a while)
      
## Describe the bug
What the bug is.
  command line ddgs returns 1 result then hangs until CTL-C to abort. I have waited as long as 25 minutes for additional results

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
from macos terminal:
  ddgs text -k "open source ai agent" -r en-us -s off -m 5

Actual keywords do not change the outcome nor does using text or news.

**Specify this information**

 - OS: macOS 14.4.1
 - environment: conda ?
 - duckduckgo_search version: tried 5.3.1 and 5.3.1b1

**Comment by jonny7737** [comment]
It has been some time since I last used ddg cli tool so I cannot say when this started. I have uninstall ddg and installed 5.3.0 - same 1 result and hang behavior. 

I am uncertain if this is an environment problem or a bug in ddg.

**Comment by deedy5** [comment]
@jonny7737
CLI version prints the result in the terminal 1 result at a time. Just press "Enter" to see the rest of the results.

**Comment by jonny7737** [comment]
HAHAHAHAHA!
Thanks!
