### ISSUE TITLE
RatelimitException 

### ISSUE THREAD

**Issue by abelkm99** [deedy5/duckduckgo_search#215]
**Before you open an issue:**
- [x] I have the latest version. (Check: `ddgs version`. Update: `pip install -U duckduckgo_search`)</br>
- [x] I tried reinstalling the library. (`pip install -I duckduckgo_search`)
- [x] https://duckduckgo.com is accessible in my browser
- [x] I tried using a proxy (the site may block ip for a while)
      
## Describe the bug
Installed the package in a new environment with the latest version.
Run the example code
`ddgs text -k "axon regeneration"`
got the following error
`RatelimitException: https://links.duckduckgo.com/d.js?q=axon+regeneration&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-237456488976888892595880207313027195381&ex=-1 202 Ratelimit`

got the same result with the python code from the examples as well

What the bug is.
RatelimitException even though it's just my first request.

**Specify this information**

 - OS :- mac os(14.2.1)
 - environment:-  python virtual environment (python 3.11)
 - duckduckgo_search version :- 5.3.1

**Comment by deedy5** [comment]
Does version v5.3.1b1 work?
`pip install -U duckduckgo_search==5.3.1b1`

**Comment by abelkm99** [comment]
hey @deedy5 
It's Working now.
It's fair this issue is going to came back again, cause this is my third time encountering it. what's the reason for the issue ?

**Comment by deedy5** [comment]
v6.0.0
