### ISSUE TITLE
DDGS Search is not working

### ISSUE THREAD

**Issue by hereisSwapnil** [deedy5/duckduckgo_search#217]
**Before you open an issue:**
- [x] I have the latest version. (Check: `ddgs version`. Update: `pip install -U duckduckgo_search`)</br>
- [x] I tried reinstalling the library. (`pip install -I duckduckgo_search`)
- [x] https://duckduckgo.com is accessible in my browser
- [ ] I tried using a proxy (the site may block ip for a while)
      
## Describe the bug

I am not able to search from the API it is showing error
![image](https://github.com/deedy5/duckduckgo_search/assets/85278243/9ecd49d5-c060-4bce-9d60-52754b15257c)

## Error Screenshot
![image](https://github.com/deedy5/duckduckgo_search/assets/85278243/b85e0c4b-13d6-4726-b702-8a6648430a69)

**Comment by hereisSwapnil** [comment]
@deedy5 please help

**Comment by cyc00518** [comment]
same error...

**Comment by deedy5** [comment]
- [ ] https://duckduckgo.com is accessible in my browser

Check it out. There's some kind of problem on the site.

**Comment by deedy5** [comment]
Does the error still arise?

**Comment by hereisSwapnil** [comment]
@deedy5 it is working now

**Comment by gee842** [comment]
https://downdetector.co.uk/status/duckduckgo/

There is an issue with DDG itself it seems
