### ISSUE TITLE
Facing the Ratelimit problem

### ISSUE THREAD

**Issue by smartliuhw** [deedy5/duckduckgo_search#218]
**Before you open an issue:**
- [x] I have the latest version. (Check: `ddgs version`. Update: `pip install -U duckduckgo_search`)</br>
- [x] I tried reinstalling the library. (`pip install -I duckduckgo_search`)
- [ ] https://duckduckgo.com is accessible in my browser
- [ ] I tried using a proxy (the site may block ip for a while)
      
## Describe the bug

I'm using this repo to retrieve a dataset (with about 10k datas) to get the knowledge. But soon I got the Ratelimit error. I could get the results at the beginning. Is it beacause my IP was blocked or there's some bug in the newest version? I have set a 1 second interval between each request, but a multiprocessing was used in my code. Is there any suggestion?

**Specify this information**

 - OS AlmaLinux release 9.2(RedHat)
 - environment python3.10
 - duckduckgo_search version 6.1.0

**Comment by smartliuhw** [comment]
> There's some kind of problem on the site.

I see, is there anything we can do to fix it?

**Comment by jonny7737** [comment]
The issue is with Microsoft aka: Bing, Copilot and ChatGPT.

**Comment by gee842** [comment]
I also am facing the same issue. the website works for me and I am calling the library on its own without the use of other tools.

**Comment by deedy5** [comment]
Does the error still arise?

**Comment by smartliuhw** [comment]
> Does the error still arise?

Now single thread can run, thank you very much for your answer. Do you have any suggestions on request frequency? Can I open multiple threads to make requests? What is the appropriate interval between

**Comment by deedy5** [comment]
If you send requests too often, the site may block your ip.
