### ISSUE TITLE
Number of search results capped at 500

### ISSUE THREAD

**Issue by grschneider** [deedy5/duckduckgo_search#221]
Is there any way to get more then 500 search results for a query?

Sample code:

```
from duckduckgo_search import DDGS
res = DDGS().text("Python", max_results=10000)
len(res)
```
Gives "500"

Windows 11
python 3.10.6
duckduckgo_search 6.1.2

**Comment by deedy5** [comment]
Update to v6.1.4, `text()` max_results cutoff 2000
