### ISSUE TITLE
Region Issue

### ISSUE THREAD

**Issue by LuccasLuz** [deedy5/duckduckgo_search#222]
**Before you open an issue:**
- [X] I have the latest version. (Check: `ddgs version`. Update: `pip install -U duckduckgo_search`)</br>
- [X] I tried reinstalling the library. (`pip install -I duckduckgo_search`)
- [X] https://duckduckgo.com is accessible in my browser
- [X] I tried using a proxy (the site may block ip for a while)
      
## Describe the bug

Good morning! I'm from Brazil and i'm trying to search results for some companies. When i try to search directly on the duckduckgo website with no region filter, it returns some results, but when i try through the async duckduckgo_search (text) with default region, it returns US response. Even if i try to set region as 'br-pt', the results are the same, US based. I need to get not the US based response, but 'br-pt' response or no region at all response. Can you guys help me on this?

I'm using this version: duckduckgo_search==5.3.0b4

Update: Tried updating the lib to 6.1.4 but still returned results US based even with 'br-pt' region set.

**Comment by deedy5** [comment]
Olá!
Fixed in v6.1.5
