### ISSUE TITLE
IndexError: list index out of range with HTML backend, specific query, large max_results.

### ISSUE THREAD

**Issue by talmichael1** [deedy5/duckduckgo_search#239]
**Before you open an issue:**
- [+] I have the latest version. (Check: `ddgs version`. Update: `pip install -U duckduckgo_search`)</br>
- [+] I tried reinstalling the library. (`pip install -I duckduckgo_search`)
- [+] https://duckduckgo.com is accessible in my browser
- [+] I tried using a proxy (the site may block ip for a while)
      
## Describe the bug

When using a very precise query like: plumber site:nicepage.io and using a large max_results=200 IndexError: list index out of range is given. Seems to work normally with the API backend, but not with the HTML backend. 

Here is a code example:
ddg = DDGS()
results = ddg.text("plumber site:nicepage.io", safesearch='off', region='wt-wt', max_results=200, backend='html')

**Steps to reproduce the problem:**
1. Specific query
2. Large max_results
3. HTML backend

**Specify this information**

 - Mac os and Heroku dynos (Heroku 22)
 - duckduckgo_search version = 6.2.0

**Comment by deedy5** [comment]
@talmichael1 Thanks! Fixed in v6.2.1
