### ISSUE TITLE
safesearch off not working as expected 

### ISSUE THREAD

**Issue by RaSan147** [deedy5/duckduckgo_search#24]
Searching anything adult (of course we are human and have weird thoughts sometimes) with safesearch "Off", results response same as moderate, doing the same search on browser with safe search off gives proper results.

Can you kindly check...

**Comment by deedy5** [comment]
Thanks. https://github.com/deedy5/duckduckgo_search/pull/25
Please update to version [v2.4.0](https://github.com/deedy5/duckduckgo_search/releases/tag/v2.4.0)
