### ISSUE TITLE
RuntimeError: Unknown impersonate version: edge_99

### ISSUE THREAD

**Issue by Hendler** [deedy5/duckduckgo_search#244]
**Before you open an issue:**
- [x] I have the latest version. (Check: `ddgs version`. Update: `pip install -U duckduckgo_search`)</br>
- [x] I tried reinstalling the library. (`pip install -I duckduckgo_search`)
- [x] https://duckduckgo.com is accessible in my browser
- [x] I tried using a proxy (the site may block ip for a while)
      
## Describe the bug

Occasionally pulls up unknown impersonate version on instantiation. 

`RuntimeError: Unknown impersonate version: edge_99`

What the bug is.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Specify this information**

 - OS - Mac OS
 - environment python 3.11-dev
 - duckduckgo_search version    6.2.7

**Comment by deedy5** [comment]
Thanks!
Fixed in v6.2.8
