### ISSUE TITLE
Allow custom date range in search

### ISSUE THREAD

**Issue by alybel** [deedy5/duckduckgo_search#246]
**Describe the solution you'd like**
I am using the DDGS().text("search string") feature in Python. It does provide a timelimit (e.g. "y"), but the custom date functionality provided by DDG does not seem to be implemented. It would be a very nice feature though. 

<img width="795" alt="image" src="https://github.com/user-attachments/assets/cbacc9a5-3265-46ad-b0c9-514abc4fc9b2">

**Comment by deedy5** [comment]
https://github.com/deedy5/duckduckgo_search/issues/86
