### ISSUE TITLE
URL normalization util misses spaces encoded as `%20`

### ISSUE THREAD

**Issue by dgw** [deedy5/duckduckgo_search#247]
**Before you open an issue:**
- [x] I have the latest version. (Check: `ddgs version`. Update: `pip install -U duckduckgo_search`)
- [x] I tried reinstalling the library. (`pip install -I duckduckgo_search`)
- [x] https://duckduckgo.com is accessible in my browser
- [ ] I tried using a proxy (the site may block ip for a while)

_This is about a library utility function, not a problem talking to DDG, so I have skipped the proxy step as the bug isn't related to DDG blocking me._

## Describe the bug

In the `_normalize_url` function, it is possible for raw spaces to slip through:

https://github.com/deedy5/duckduckgo_search/blob/5c0e9ec05b39afb40419279611efe71c5c89e8b6/duckduckgo_search/utils.py#L74-L76

Bare spaces are replaced with `+` before unquoting the input, meaning spaces that are already encoded as `%20` don't become `+`.

**Steps to reproduce the problem:**
Normalize a URL containing `%20` escapes, e.g. `utils._normalize_url('https://www.google.com/?q=bug%20here')` (returns `https://www.google.com/?q=bug here`, rather than `https://www.google.com/?q=bug+here`)

**Specify this information**

 - OS: Linux (various Debian-derivs
 - environment: tested python 3.10, 3.11, 3.12
 - duckduckgo_search version: 6.2.10

**Comment by deedy5** [comment]
Thanks!
Fixed in v6.2.11

**Comment by dgw** [comment]
Updated to the new release and tested a few queries that previously exhibited this bug; they now use `+` as expected.

Thanks for the quick fix!
