### ISSUE TITLE
Resume previous Search for Images with previous downloaded image state and only download new image which haven't been downloaded yet / Recude duplicate Downloads

### ISSUE THREAD

**Issue by Snickbrack** [deedy5/duckduckgo_search#250]
Example Query for reference:
`ddgs images -k "hitman game" -r wt-wt -type photo -m 5 -d`

![image](https://github.com/user-attachments/assets/0e2cf988-5c4e-4c4d-a516-0a4a3d284b8e)

Result:
![image](https://github.com/user-attachments/assets/bad27d27-855f-4608-b7ef-756c7b7eed64)

Folder 1:
![image](https://github.com/user-attachments/assets/db28a41b-8507-4878-840a-1c0dfaa8bb9f)

Folder 2:
![image](https://github.com/user-attachments/assets/e6bd1499-2341-4d82-bb3a-1008ae49d3b8)

**Is your feature request related to a problem? Please describe.**
For each Query to the same keywords a new directory is opened and the same Images will be saved. (Or small differences)

**Describe the solution you'd like**
That I can specify (maybe with a new parameter -r (for resume)) if DDGS should only fetch and download images that aren't available in my previously created directory or in a state-file.

**Describe alternatives you've considered**
As of now I can't think of an alternative besides an Index-Value which tells DDGS what number of images I already have and only fetch the images with greater index from the API.

I assume that the API returns a pagable response so one could skip Pages which should contain a somewhat fixed amount of elements. So when I say skip X Elements it should skip the first Y pages and the remaining Elements. (Pseudo-Code :D )

**Additional context**
none

**Comment by deedy5** [comment]
The results of image searches are always partially different, so it is not possible to compare images based on their indexes. 

Images are not always downloaded successfully due to various reasons - inaccessible url, blocking by ISP or the site itself.

What you want to do requires working with images and their comparison, most likely it is possible to do it, but it goes far beyond the tasks of this package.
