### ISSUE TITLE
How to avoid Ratelimit problem?

### ISSUE THREAD

**Issue by cyc00518** [deedy5/duckduckgo_search#254]
Hello, thank you for your excellent work.

I would like to integrate DuckDuckGo into my LLM service. 
Could you let me know how many requests I can make per minute without encountering `Ratelimit`  issues?

Additionally, if my IP gets blocked, how long does it take to get unblocked?

**Comment by MrLightspeed** [comment]
I am glad you commented as I have just noticed a lot of rate limit issues as of yesterday.

Perhaps something changed in need of an update?

**Comment by ptung611** [comment]
+1 I'm always face the Rate limit issues with DDGS().text from yesterday. 

`duckduckgo_search.exceptions.RatelimitException: https://duckduckgo.com/ 202 Ratelimit`

**Comment by satounity** [comment]
It is no longer possible to use this service due to rate limit. Please take action.

**Comment by deedy5** [comment]
fixed in v6.3.0

**Comment by cyc00518** [comment]
@deedy5 
Thanks!

Would you mind sharing how many requests I can make per minute without encountering Ratelimit issues in the future?

**Comment by HarshVardhanKumar** [comment]
Hi. Still getting the rate_limit error even after update to version 6.3.0, still not useful. Thanks.

**Comment by HarshVardhanKumar** [comment]
Hi. The rate limit is not observed in v6.3.0, but the requests are getting timed out.

RuntimeError: error sending request for url (https://duckduckgo.com/?q=parthenophe): operation timed out

**Comment by ovidysus0** [comment]
I'm actually still getting the rate limit issue, and whatever the rate limit is seems to be quite low. 

Params:

`atext(base_query, region='us-en', safesearch='off', max_results=10, backend='lite')`

I've tried without backend specified, and I've tried initializing the class with 2 different proxy pools, both of which have worked for me in the past, but now I keep getting 202's.

**Comment by Knowerbescheidt** [comment]
First of thank you for your work on this awesome package <3 !
I also still encounter a ratelimit error, my calling code:
`web_responses: list[dict] = DDGS().text(
        query, max_results=MAX_SEARCH_RESULTS
    )`
it started a couple of days ago. And I would also like to know about the ratelimit.

**Comment by sanexodus** [comment]
Hi, Firstly, thanks for the great work. I installed the latest 6.3.0 version, but still got 202 Ratelimit exception.

**Comment by leslie2046** [comment]
https://links.duckduckgo.com/d.js?q=%E5%B7%A5%E8%A1%8C+%E5%A6%82%E6%84%8F%E7%A7%AF%E5%AD%98%E9%87%91+2024%E5%B9%B410%E6%9C%88&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-207594998297090001367987456061024957611&bing_market=wt-WT&ex=-1 202 Ratelimit

**Comment by JaheimLee** [comment]
still got Ratelimit @deedy5

**Comment by sabatale** [comment]
Same here.

**Comment by deedy5** [comment]
The upstream api has known and unknown limits on the number of requests per unit time. Single requests or requests in the same thread should not cause errors. 

Simply reporting that you got this error has no informational value. Context is important - how you use the code, in one/more threads, what parameters you use in a function, etc.
