### ISSUE TITLE
Enable passing certificate store or certificate verification to `primp`

### ISSUE THREAD

**Issue by matt-dies-tenet3** [deedy5/duckduckgo_search#257]
**Is your feature request related to a problem? Please describe.**
When creating a `DDGS` object, this will fail if the certificate chain contains a self-signed certificate. In some cases, using a self-signed certificate is mandatory/strongly desired, such as corporate environments. `primp` [enables certificate-related configuration](https://github.com/deedy5/primp/blob/main/src/lib.rs#L68-69), so it would be nice if the `DDGS` object enabled similar configurations.

**Describe the solution you'd like**
The `DDGS` object could contain optional variables on initialization to configure these settings. For example:
```python
from pathlib import Path

def __init__(
    self,
    headers: dict[str, str] | None = None,
    proxy: str | None = None,
    proxies: dict[str, str] | str | None = None,  # deprecated
    ca_cert_file: Path | str | None = None,
    verify_ssl: bool = True,
    timeout: int | None = 10,
) -> None:
    if ca_cert_file is not None:
        ca_cert_file = str(ca_cert_file)

    # later...
    self.client = primp.Client(
        headers=self.headers,
        proxy=self.proxy,
        timeout=timeout,
        cookie_store=True,
        referer=True,
        impersonate=choice(self._impersonates),
        follow_redirects=False,
        ca_cert_file=ca_cert_file,
        verify=verify_ssl,
    )
```

It would also be really nice to have a way to configure these options when using the CLI. This could include environment variables, e.g., `DDGS_CERT_FILE=<my_cert_file_path> ddgs text -k "foo"`. Alternatively they could be options provided to the tool: `ddgs --cert-file <my_cert_file_path> text -k "foo"`.

**Describe alternatives you've considered**
The alternative is to, well, not use the package. If the self-signed certificate is mandatory, this makes usage of the package impossible without the ability to whitelist the `duckduckgo.com` domain.

**Additional context**
When a command fails because of this, it raises this error:
```
DuckDuckGoSearchException: https://duckduckgo.com RuntimeError: error sending request for url (https://duckduckgo.com/?q=foo): error trying to connect: TLS handshake failed: cert verification failed - self signed certificate in certificate chain [CERTIFICATE_VERIFY_FAILED]

Caused by:
    0: error trying to connect: TLS handshake failed: cert verification failed - self signed certificate in certificate chain [CERTIFICATE_VERIFY_FAILED]
    1: TLS handshake failed: cert verification failed - self signed certificate in certificate chain [CERTIFICATE_VERIFY_FAILED]
    2: [CERTIFICATE_VERIFY_FAILED]
    3: [CERTIFICATE_VERIFY_FAILED]
```

**Comment by deedy5** [comment]
Can you please explain how you got this error?

`primp` compiles with Mozilla's trusted root certificates (https://github.com/rustls/webpki-roots)
https://github.com/deedy5/rquest/blob/c1e0d5072342d37597f6bf40a1c06baecbf92b22/Cargo.toml#L20C1-L21C52

And by default, they're the same ones used:
https://github.com/deedy5/rquest/blob/1adc74c89cd7b7f74b5c73e044718f6b1cbbb41f/src/tls/mod.rs#L101-L135

How can it be that the certificate chain contains a self-signed certificate?

**Comment by PhMota** [comment]
I am having the same error here. Also behind a corporate network. It was working a week ago.

**Comment by deedy5** [comment]
The 'verify' parameter was added in version v6.3.2

```python
from duckduckgo_search import DDGS

results = DDGS(verify=False).text("python", max_results=5)
print(results)
```
CLI
```
ddgs text -k 'python 3.13' --verify false
ddgs text -k 'python 3.13' -v f
ddgs text -k 'python 3.13' -v n
```

**Comment by deedy5** [comment]
You can pass a cert file to primp using environment variable PRIMP_CA_BUNDLE:
 ```python
export PRIMP_CA_BUNDLE="/etc/cert.pem"
```
