### ISSUE TITLE
Downloading files asociated to a key search

### ISSUE THREAD

**Issue by vjvelascorios** [deedy5/duckduckgo_search#26]
Thanks so much, this is a fantastic project and I hope still alive for much time.

Just as a kindly suggestion, should be fantastic adding a new function for downloading files associated to a key term, like pdf's, pptx's, like `ddgs document`.

Again, thanks for such powerful package.
Regards.

**Comment by deedy5** [comment]
Thank you.

https://github.com/deedy5/duckduckgo_search/pull/27
[v2.5.0](https://github.com/deedy5/duckduckgo_search/releases/tag/v2.5.0)

The ddg() function can now download results to a local disk in the same way as ddg_images()
This is also possible in the CLI version. 
Examples:

```python3
ddgs text -k "robinson r44 filetype:pdf" -m 250 -o None -d
```
```python3
ddgs text -k "robinson r44 filetype:docs" -m 250 -o None -d
```
```python3
ddgs text -k "robinson r44 filetype:xlsx" -m 250 -o None -d
```

**Comment by vjvelascorios** [comment]
Wow,
Thank you so much.
