### ISSUE TITLE
`ShareCommercially` does not work in CLI

### ISSUE THREAD

**Issue by rbozan** [deedy5/duckduckgo_search#260]
https://github.com/deedy5/duckduckgo_search/blob/6e4b4327f8ac9c5d8abcaab148f14e8277a2ae38/duckduckgo_search/cli.py#L271

`ShareCommercially` is in the README but it's not possible to supply it here.

(by the way, is there no way to supply multiple licenses?)

**Comment by deedy5** [comment]
fixed in v6.3.4
