### ISSUE TITLE
CLI not output on CSV/JSON formats

### ISSUE THREAD

**Issue by IvanIvanerov** [deedy5/duckduckgo_search#36]
i tested in different parts (images/news) with different output options (csv/json) and different safety options.
No one has visible results

**Comment by deedy5** [comment]
Hello and Thank you! 

Please show me your code, so I can reproduce your steps and see the problem.

**Comment by IvanIvanerov** [comment]
ddgs images -k "emma hewitt" -m 10 -o json

**Comment by deedy5** [comment]
The json or csv file is saved in the same folder where you ran the command in the terminal.
You should change to the correct directory before running the command.

For example, go to the root of drive C:
C:\Users\User `C:`
C:\ `ddgs images -k "emma hewitt" -m 10 -o json`
Now look at the files in the root of the C:\ drive.

**Comment by IvanIvanerov** [comment]
can you upgrade script to stdout and double quote in JSON against single quote?

**Comment by deedy5** [comment]
I don't understand the question
