### ISSUE TITLE
_normalize removes apostrophes from search results

### ISSUE THREAD

**Issue by rmfrt** [deedy5/duckduckgo_search#37]
In ddg.py, line 54 `body = _normalize(row["a"])` removes the apostrophe characters (`&#x27;`) which makes the search result less readable (same for `"title": _normalize(row["t"]),` on line 58). 
From the examples on the duckduckgo_search GitHub page, this seems to be a problem that did not exist previously.
Removing the apostrophe is particularly problematic in French, this character is frequently used, the results are no longer understandable.
Thanks!

**Comment by deedy5** [comment]
Thank you for finding this bug. Fixed in version 2.8.1.
You can update the package with the command `pip install -U duckduckgo_search`.
