### ISSUE TITLE
After a number of requests ddg returns an empty list

### ISSUE THREAD

**Issue by eulenleber** [deedy5/duckduckgo_search#38]
ref https://github.com/deedy5/duckduckgo_search/issues/35
Lets track that here:

```python
import duckduckgo_search
a=True
i=0
while a:
    a=duckduckgo_search.ddg('"test test"')
    print(f"{i} {len(a)}")
    i+=1
```
returns eventually `[]`
b.c. duckduckgo returns
```
window.execDeep=function(){return{is506:1,bn:{ivc:1,ibc:0}};};
```

**Comment by deedy5** [comment]
if the max_results parameter is not specified and an exception occurs when requesting the api, it will return None.
Fixed in [v2.8.3](https://github.com/deedy5/duckduckgo_search/releases/tag/v2.8.3).
Please update and retray.
```python3
pip install -U duckduckgo_search
```
