### ISSUE TITLE
max_results parameter is misleading

### ISSUE THREAD

**Issue by szmejap** [deedy5/duckduckgo_search#5]
Hello,

The max_results parameter does not represent the maximum, but rather the minimum number of results. I noticed, that there is a hardcoded increment value for individual functions (different for ddg_news, ddg_images, etc), by which the number of results is increased, in batches, until the total number of results is larger, that max_results.

The easiest fix, would be to rename max_results, to min_results.

Additionally, the increment value could be exposed via an additional parameter (fetch_increment).

In any case, this is not critical. I understand not wanting to introduce a parameter name change, that would break backwards compatibility for such a trivial thing, but the actual meaning of max_results should be documented.

Cheers,
Pawel

**Comment by deedy5** [comment]
Hello.
Thank you for your participation, I will add a fix to the code shortly.
