### ISSUE TITLE
ddg_answers returns empty result

### ISSUE THREAD

**Issue by sergeykorablin** [deedy5/duckduckgo_search#51]
I have this simple script and `ddg` works as expected but `ddg_answers` always returns empty array:
```python
from duckduckgo_search import ddg
from duckduckgo_search import ddg_answers

keywords = 'USD to EUR exchange rate'

results = ddg(keywords, safesearch='Off', time='y')
print(results[0])

results = ddg_answers(keywords, related=True)
print(results)
```

{'title': 'US-Dollar to Euro Conversion | USD to EUR Exchange Rate Calculator ...', 'href': 'some link', 'body': 'Quickly and easily calculate foreign exchange rates with this free currency converter....'}
[]

What I'm doing wrong?

**Comment by deedy5** [comment]
You need another function for the currency converter, but it is not implemented in this package.  
Try just sending a url-request like this `https://duckduckgo.com/js/spice/currency/1/usd/rub`

**Comment by sergeykorablin** [comment]
You're right, other queries work.
Great project, thanks!
