### ISSUE TITLE
miss match for quotation mark in utils._get_vqd

### ISSUE THREAD

**Issue by MichelZhan** [deedy5/duckduckgo_search#56]
![image](https://github.com/deedy5/duckduckgo_search/assets/24311158/ad915cfe-49cb-4383-9087-708ea354766b)
![image](https://github.com/deedy5/duckduckgo_search/assets/24311158/63931e82-e051-4384-9ba9-73f5ba53a92e)

**Comment by deedy5** [comment]
I'm already aware of it, they just changed the single quotes to double quotes.

**Comment by deedy5** [comment]
Done. Update to [v2.9.4](https://github.com/deedy5/duckduckgo_search/releases/tag/v2.9.4)

**Comment by jkemp814** [comment]
`pip install --upgrade duckduckgo-search` worked after fix by @deedy5 

Great job. Quick and timely update. Appreciate it.

**Comment by mech206117** [comment]
How to do the upgrade of duckduckgo-search package on the image which we pulled from [Docker Hub](https://hub.docker.com/r/significantgravitas/auto-gpt)

**Comment by DimbaPride** [comment]
**I have this error too**

C:\Users\caio_\AppData\Local\Programs\Python\Python310\lib\site-packages\duckduckgo_search\compat.py:20: UserWarning: ddg is deprecated. Use DDGS().text() generator
  warnings.warn("ddg is deprecated. Use DDGS().text() generator")
C:\Users\caio_\AppData\Local\Programs\Python\Python310\lib\site-packages\duckduckgo_search\compat.py:24: UserWarning: parameter page is deprecated, use DDGS().text() generator
  warnings.warn("parameter page is deprecated, use DDGS().text() generator")
C:\Users\caio_\AppData\Local\Programs\Python\Python310\lib\site-packages\duckduckgo_search\compat.py:26: UserWarning: parameter max_results is deprecated, use DDGS().text()
  warnings.warn("parameter max_results is deprecated, use DDGS().text()")
SYSTEM:  Command google returned: Error:

**Comment by cadenhewlett** [comment]
> **I have this error too**
> 
> C:\Users\caio_\AppData\Local\Programs\Python\Python310\lib\site-packages\duckduckgo_search\compat.py:20: UserWarning: ddg is deprecated. Use DDGS().text() generator warnings.warn("ddg is deprecated. Use DDGS().text() generator") C:\Users\caio_\AppData\Local\Programs\Python\Python310\lib\site-packages\duckduckgo_search\compat.py:24: UserWarning: parameter page is deprecated, use DDGS().text() generator warnings.warn("parameter page is deprecated, use DDGS().text() generator") C:\Users\caio_\AppData\Local\Programs\Python\Python310\lib\site-packages\duckduckgo_search\compat.py:26: UserWarning: parameter max_results is deprecated, use DDGS().text() warnings.warn("parameter max_results is deprecated, use DDGS().text()") SYSTEM: Command google returned: Error:

I am also currently encountering this problem, would be interested to find a fix

**Comment by deedy5** [comment]
fived in v3.4.1
`pip install -U duckduckgo-search`

**Comment by neogithub** [comment]
> > **I have this error too**
> > C:\Users\caio_\AppData\Local\Programs\Python\Python310\lib\site-packages\duckduckgo_search\compat.py:20: UserWarning: ddg is deprecated. Use DDGS().text() generator warnings.warn("ddg is deprecated. Use DDGS().text() generator") C:\Users\caio_\AppData\Local\Programs\Python\Python310\lib\site-packages\duckduckgo_search\compat.py:24: UserWarning: parameter page is deprecated, use DDGS().text() generator warnings.warn("parameter page is deprecated, use DDGS().text() generator") C:\Users\caio_\AppData\Local\Programs\Python\Python310\lib\site-packages\duckduckgo_search\compat.py:26: UserWarning: parameter max_results is deprecated, use DDGS().text() warnings.warn("parameter max_results is deprecated, use DDGS().text()") SYSTEM: Command google returned: Error:
> 
> I am also currently encountering this problem, would be interested to find a fix

Same issue even after v3.4.1 update
