### ISSUE TITLE
Syntax error in v2.9.4

### ISSUE THREAD

**Issue by VineethK336** [deedy5/duckduckgo_search#58]
Hello!

I noticed a syntax error upon trying to use the v2.9.4 version of the library. The error I faced:
![Screenshot 2023-05-12 at 10 50 37 PM](https://github.com/deedy5/duckduckgo_search/assets/25902483/0b4b9267-4379-4699-94ee-b61d0433f6ec)

The issue is in an fstring mentioned below. The **=** inside the interpolation is causing the issue.

The line in the code causing the issue: https://github.com/deedy5/duckduckgo_search/blob/main/duckduckgo_search/ddg.py#L60

**Comment by deedy5** [comment]
Yes, you're right. This appeared in python 3.8
https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging

**Comment by deedy5** [comment]
Fixed in https://github.com/deedy5/duckduckgo_search/pull/59
Please update to [v2.9.5](https://github.com/deedy5/duckduckgo_search/releases/tag/v2.9.5)
`pip install -U duckduckgo_search`

**Comment by VineethK336** [comment]
Thank you for the quick resolution!
