### ISSUE TITLE
ddg() and ddg_news() return None. 

### ISSUE THREAD

**Issue by bable631** [deedy5/duckduckgo_search#62]
I tried the proposed solution that was provided in the issue that was just closed, but it did not work. I am on the most recent version and am using python 3.10

Please help?

**Comment by deedy5** [comment]
Please run this and show the result
```python3
import logging
from duckduckgo_search import ddg

logging.basicConfig(level=logging.DEBUG)

keywords = 'Bella Ciao'
results = ddg(keywords, region='wt-wt', safesearch='Off', time='y')
print(results)
```

**Comment by deedy5** [comment]
Try using a proxy

**Comment by deedy5** [comment]
Run the Tor browser in the background.
And try this:

```python3
import logging
from duckduckgo_search import ddg
from duckduckgo_search.utils import SESSION

logging.basicConfig(level=logging.DEBUG)

SESSION.proxies = {
    "http": f"socks5h://localhost:9150",
    "https": f"socks5h://localhost:9150"
}

keywords = 'Bella Ciao'
results = ddg(keywords, region='wt-wt', safesearch='Off', time='y')
print(results)
```

**Comment by deedy5** [comment]
What about another proxy?

**Comment by bable631** [comment]
As far as I can tell, I can't setup a proxy the way you are suggesting if I'm using pythonanywhere. If it DID work when I used a proxy, what would that tell you about the issue?

**Comment by deedy5** [comment]
blocked ip

**Comment by bable631** [comment]
That makes sense. Why would my IP be blocked? Is there a solution beyond using a different IP via proxy?

**Comment by deedy5** [comment]
1) not your ip, but this site's `python IDE (pythonanywhere)`
2) https://www.google.com/search?q=Why+would+my+IP+be+blocked
3) Just use a proxy

**Comment by deedy5** [comment]
With frequent requests site used to block ip for a period of about 10 seconds, now the period of blocking is much longer (I do not know exactly, about 10-30 minutes).
