### ISSUE TITLE
ddg() returns None or an empty list

### ISSUE THREAD

**Issue by vatsal-kavida** [deedy5/duckduckgo_search#65]
I tried this code-> resp = ddg(search_query, max_results=1)  and either I get a None as my return value or an empty list, It was working fine, before last 2-3 days but now it creating this issue

**Comment by AndiTemlinski** [comment]
Same issue.

**Comment by Raamo** [comment]
Same issue.

**Comment by Undertone0809** [comment]
God! Bro here I got the same question.

**Comment by vatsal-kavida** [comment]
I tried with proxy and it worked, I guess my ip was banned

**Comment by Raamo** [comment]
> 

Can you show example how you solved it? or where toput in the proxy?

**Comment by deedy5** [comment]
https://github.com/deedy5/duckduckgo_search/releases/tag/v3.0.1

**Comment by jpe90** [comment]
Fixed for me on v3.0.2

**Comment by kryptan** [comment]
@deedy5 Thank you for keeping up with DuckDuckGo changes and keeping this library working 💖

**Comment by abondrn** [comment]
I'm on 3.0.2 currently and it always gives me an empty list
