### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by simzhangbest** [deedy5/duckduckgo_search#68]
from duckduckgo_search.utils import SESSION
ModuleNotFoundError: No module named 'duckduckgo_search.utils'

Name: duckduckgo-search
Version: 3.0.2

python version 3.8.10

**Comment by deedy5** [comment]
[using proxy](https://github.com/deedy5/duckduckgo_search#using-proxy)

**Comment by deedy5** [comment]
Then what is the purpose of importing SESSION?
