### ISSUE TITLE
Request Control

### ISSUE THREAD

**Issue by DankStats** [deedy5/duckduckgo_search#69]
Hi,

I'm not completely sure that this is an application issue per se but i noticed that DuckDuckGo blocked my ip for a couple of days while making multiple requests during a short period of time. Have you thought of creating a feature that allows the user to control the number of requests per second or something like that?

kind regards

**Comment by bishopong** [comment]
I am also facing this issue.
Is there no way to search for a specific number of results?

**Comment by deedy5** [comment]
Hi.
___
1.
In the latest version, if you run even two DDGS threads, the ip will not be blocked. 

If you start many threads, you will get a logging.warning message that the server responds with a 418 status code. 
This is a temporary lock, for 30 seconds, then everything works as before.

If you start many threads, create a separate DDGS object for each thread and use a proxy server.
___
2.
To pick up a certain number of results, you just have to stop the generator when you reach the desired number of results.
Example:
```python3
from duckduckgo_search import DDGS

#1
ddgs_gen = DDGS().text("python generator")
results = []
for i, r in enumerate(ddgs_gen, start=1):
    if i > 2:
        break
    results.append(r)
print(results)

#2
ddgs_gen = DDGS().text("python generator")
results = []
for _ in range(2):
    results.append(next(ddgs_gen))
print(results)

#3
ddgs_gen = DDGS().text("python generator")
results = [r for i, r in enumerate(ddgs_gen) if i<2]
print(results)

#4
ddgs_gen = DDGS().text("python generator")
results = [next(ddgs_gen) for _ in range(2)]
print(results)
```
and so on...
___

B.R.
