### ISSUE TITLE
DDGS how to set max_result like ddg()

### ISSUE THREAD

**Issue by Undertone0809** [deedy5/duckduckgo_search#74]
I wonder know DDGS().text() how to set max_results like ddg()

If I use ddg()，I can do as follows.

```python
results = ddg("my query", max_result=5)
```

But I found DDGS might lose that ability. It can not use `max_result` parameter. Will `max_result` be provided for `DDGS` in the future?

**Comment by armysarge** [comment]
Having the same issue

**Comment by deedy5** [comment]
The generator doesn't aggregate the data, it yields one at a time. 
That is, if I add this parameter again, it will just be a counter that will stop the generator when it gives the right number of results.

**Comment by kinance** [comment]
I migrated our code to new DDGS.text func and use islice to limit the max result for backward comp. In case any interest, please see https://github.com/Significant-Gravitas/Auto-GPT/pull/4383/files.

**Comment by Undertone0809** [comment]
> I migrated our code to new DDGS.text func and use islice to limit the max result for backward comp. In case any interest, please see https://github.com/Significant-Gravitas/Auto-GPT/pull/4383/files.

A good solution！
