### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jorigel** [deedy5/duckduckgo_search#76]
Hi,
using s.th. like Your example leads to the following:

```
ddgs images -k "lego" -m 10 -d
File "/usr/local/lib/python3.11/dist-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://duckduckgo.com/i.js?l=wt-wt&o=json&s=0&q=lego&vqd=4-332562653244607921904828071066005263548&f=%2C%2C%2C%2C%2C&p=1
```

**Comment by deedy5** [comment]
Change your ip and don't use packages that parse the site via html.

**Comment by jorigel** [comment]
Hi, thanks for Ur help.
Changing the ip-address  of the router is what You mean? That doesn't help. 
What means "don't use packages that parse the site via html". I didn't do any parsing at all.  
I'm just using the command, like U did:

`ddgs images -k "lego" -m 10 -d`

regards jori

**Comment by deedy5** [comment]
I issued a fix, update to version v3.4.0

**Comment by gambastyle** [comment]
also having the same problem 3.4.1 did not fix it

**Comment by GordonLevy** [comment]
same issue - v3.4.1

**Comment by deedy5** [comment]
[link](https://github.com/deedy5/duckduckgo_search#1-text---text-search-by-by-duckduckgocom)
WARNING!: Since version v3.4.0, api requests have been replaced by html parsing. Set a delay of at least 1 second between function calls.

**Comment by jorigel** [comment]
Hi deedy5,
basically I had at least 30 seconds between the calls, but to test it carefully I inserted a exit(0) after the first call. That didn't make any difference -> the error persists even after resetting the ip on the router.
```
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://duckduckgo.com/i.js?l=wt-wt&o=json&s=0&q=Freilich&vqd=4-247041414588049212891110274469183150429&f=%2C%2C%2C%2C%2C&p=-1
```
and on top of that using Ur cli-command
`ddgs images -k "lego" -m 10 -d`
triggers the function call only once as far as I concern and even that shows the error  (also after resetting the ip on the router). Don't U see the error after calling Your cli-command Urself?

There must be s.th. different in the way DDG handles these calls. B.t.w. U are not the only one fighting with this. Others who offer DDG-calls via their libs seem to have the same issues.

regards
jori

**Comment by deedy5** [comment]
In my case, the script works.
Show me how I can reproduce the problem.
Are you sure that your ip is changing?

**Comment by jorigel** [comment]
Yes, sure what ever U need:
first the system:
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.04
Release:	23.04
Codename:	lunar
```
and Version of python:
```
python3 --version
Python 3.11.2
```
and I use a normal user no root!

here the first info of my fritz-box:
```
[DSL]
verbunden, ↓ 55,2 Mbit/s ↑ 11,3 Mbit/s
Internet, IPv4

verbunden seit 26.05.2023, 12:40 Uhr, EWE - swb - osnatel (ALL-IP-Anschluss),
IP-Adresse: 85.16.200.61
Genutzte DNS-Server 	
 
212.6.64.14 (aktuell genutzt für Standardanfragen)
212.6.108.140

```
here after ip-change:

```
DSL 
verbunden, ↓ 55,2 Mbit/s ↑ 11,3 Mbit/s

Internet, IPv4  verbunden seit 26.05.2023, 13:47 Uhr, EWE - swb - osnatel (ALL-IP-Anschluss),
IP-Adresse: 85.16.203.51
Genutzte DNS-Server  212.6.64.14(aktuell genutzt für Standardanfragen)212.6.108.140
```
and here the cli-command with complete message-list including the error:
```
ddgs images -k "lego" -m 10 -d
Traceback (most recent call last):
  File "/home/piet/.local/bin/ddgs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1688, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/piet/.local/lib/python3.11/site-packages/duckduckgo_search/cli.py", line 319, in images
    for r in DDGS().images(keywords=keywords, *args, **kwargs):
  File "/home/piet/.local/lib/python3.11/site-packages/duckduckgo_search/duckduckgo_search.py", line 313, in images
    resp = self._get_url("GET", "https://duckduckgo.com/i.js", params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/piet/.local/lib/python3.11/site-packages/duckduckgo_search/duckduckgo_search.py", line 70, in _get_url
    raise ex
  File "/home/piet/.local/lib/python3.11/site-packages/duckduckgo_search/duckduckgo_search.py", line 64, in _get_url
    resp.raise_for_status()
  File "/home/piet/.local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://duckduckgo.com/i.js?l=wt-wt&o=json&s=0&q=lego&vqd=4-332546727750082285830195684950048162700&f=%2C%2C%2C%2C%2C&p=1
```
Your lib is installed via :
`pip3 install duckduckgo_search`

and confirms in:
```
pip3 list | grep duckduckgo
duckduckgo-search            3.4.1
```
I can't think of anything else necessary for U yet, do U?
regards
jori

**Comment by deedy5** [comment]
Does this url, where the error occurred, open in the browser?
https://duckduckgo.com/i.js?l=wt-wt&o=json&s=0&q=lego&vqd=4-332546727750082285830195684950048162700&f=%2C%2C%2C%2C%2C&p=1

**Comment by jorigel** [comment]
Hi,
with "where the error occurred" you mean the machine in it's surrounding not the window, don't U?
u.t.c.:
yes, it does:

![Bildschirmfoto_2023-05-26_16-14-49](https://github.com/deedy5/duckduckgo_search/assets/5578691/0ed03e39-c7bb-4241-b8c8-4237c5702f39)

**Comment by deedy5** [comment]
I don't get it. You run a command in the terminal on your computer and it returns an error. And yet the url that caused the error opens freely in a browser on the same computer?
