### ISSUE TITLE
[BUG] DDGS Text Query

### ISSUE THREAD

**Issue by GordonLevy** [deedy5/duckduckgo_search#79]
duckduckgo_search v3.4.1 for text query fails with below err:

```
from duckduckgo_search import DDGS

ddgs = DDGS()

keywords = 'Bella Ciao'
ddgs_text_gen = ddgs.text(keywords)
for r in ddgs_text_gen:
	print(r)
```

```
 raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://html.duckduckgo.com/html
```

**Comment by gambastyle** [comment]
Same, even with proxy

**Comment by deedy5** [comment]
[link](https://github.com/deedy5/duckduckgo_search#1-text---text-search-by-by-duckduckgocom)
WARNING!: Since version v3.4.0, api requests have been replaced by html parsing. Set a delay of at least 1 second between function calls.
