### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://html.duckduckgo.com/html

### ISSUE THREAD

**Issue by srtj** [deedy5/duckduckgo_search#83]
error:requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://html.duckduckgo.com/html  

when i use this code:
          ddgs_text_gen = ddgs.text(keywords, region='wt-wt', safesearch='Off', timelimit='y')

**Comment by deedy5** [comment]
There is not enough information in the issue
