### ISSUE TITLE
some dorks with '"' don't work

### ISSUE THREAD

**Issue by sandyboxy** [deedy5/duckduckgo_search#97]
**Describe the bug**
Some dorks don't work such as `q = 'site:linkedin.com "wikipedia"'`
This is my piece of code:
```
q = 'site:linkedin.com "{}"'.format(name)
with DDGS() as ddg:
	ddg_res = ddg.text(q)
```
It returns: _Wikipedia, the Free Encyclopedia | 13,303 followers on LinkedIn. Imagine a world in which every single human being can freely share in the sum of all knowledge. | Wikipedia is a multilingual ..._
While, if I make the query via DDG gui I have the following result: _About us. Wikipedia is a multilingual online encyclopedia, based on open collaboration through a wiki-based content editing system. Website. https://www.wikipedia.org/. Industries. Software_

it seems like it doesn't work the query with '`"`'

**Specify this information**
 - OS: Ubuntu
 - environment: python 3.8.10
 - duckduckgo_search version: 3.8.3

**Comment by deedy5** [comment]
![scr](https://github.com/deedy5/duckduckgo_search/assets/65482418/16c24d86-4fb6-4cee-b469-90f4610c9e62)
